import{i as c,a as S,S as q}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const f=document.querySelector(".form"),p=document.querySelector(".gallery"),I=document.querySelector(".container"),$=document.querySelector("input"),m=document.querySelector(".btn-load");let l=1,h=40,i="",y;const g=()=>{const e=document.createElement("span");e.classList.add("loader"),I.appendChild(e)},u=()=>{const e=document.querySelector(".loader");e&&e.remove()},v=()=>{m.style.display="block"},a=()=>{m.style.display="none"};f.addEventListener("submit",async e=>{if(e.preventDefault(),l=1,g(),p.innerHTML="",i=$.value.trim(),i===""){a(),c.error({message:"Please enter a search term.",position:"center",transitionIn:"fadeInLeft"}),u();return}try{const t=await b(i,l);w(t),f.reset(),u(),v(),t.hits.length<h&&a(),t.hits.length===0&&(a(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",transitionIn:"fadeInLeft"}))}catch(t){L(t)}});m.addEventListener("click",async()=>{g();try{l+=1;const e=await b(i,l);w(e),u();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),(p.children.length>=y||e.hits.length<h)&&(c.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),a())}catch(e){L(e)}});async function b(e,t){try{const o="your_api_key_here",s=await S.get(`https://pixabay.com/api/?key=${o}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${h}`);return y=s.data.totalHits,s.data}catch(o){throw console.log(o),new Error("Failed to fetch images")}}const E=new q(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250});function w(e){const t=e.hits.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}">
        </a>
        <p><b>Likes: </b>${o.likes}</p>
        <p><b>Views: </b>${o.views}</p>
        <p><b>Comments: </b>${o.comments}</p>
        <p><b>Downloads: </b>${o.downloads}</p>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function L(e){c.error({title:"Error",message:e.message})}
//# sourceMappingURL=commonHelpers.js.map
