import{i as s,a as L,S}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&h(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function h(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const f=document.querySelector(".form"),d=document.querySelector(".gallery"),q=document.querySelector(".container"),I=document.querySelector("input"),p=document.querySelector(".btn-load"),y=()=>{const e=document.createElement("span");e.classList.add("loader"),q.append(e)},a=()=>{const e=document.querySelector(".loader");e&&e.remove()},v=()=>{p.style.display="block"},i=()=>{p.style.display="none"};let u=1,m=40,l="",g;f.addEventListener("submit",async e=>{if(u=1,y(),d.innerHTML=" ",e.preventDefault(),l=I.value.trim(),l===""){i(),s.error({message:"Please enter a search term.",position:"center",transitionIn:"fadeInLeft"}),a();return}try{const r=await b();w(r),f.reset(),a(),v(),r.hits.length<m&&i(),r.hits.length===0&&(i(),s.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}))}catch{s.error({title:"Error"})}});p.addEventListener("click",async()=>{y();try{u+=1;const e=await b();w(e),a();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(d.children.length>=g||e.hits.length<m)&&(s.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),i())}catch{s.error({title:"Error"}),a()}});async function b(){try{const e="41764579-b97d65b31c0abd4efd9d4830e",r=new URLSearchParams({key:e,q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,page:u,per_page:m}),o=await L.get(`https://pixabay.com/api/?${r}`);return g=o.data.totalHits,o.data}catch(e){throw console.log(e),WebTransportError}}const E=new S(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250});function w(e){const r=e.hits.map(o=>`
            <li class="gallery-item"><a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </li>`).join("");d.insertAdjacentHTML("beforeend",r),E.on("show.simplelightbox").refresh(),a()}
//# sourceMappingURL=commonHelpers.js.map
