import{i as c,a as L,S}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))h(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&h(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function h(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const I="your_api_key_here",f=document.querySelector(".form"),d=document.querySelector(".gallery"),q=document.querySelector(".container"),v=document.querySelector("input"),u=document.querySelector(".btn-load"),y=()=>{const e=document.createElement("span");e.classList.add("loader"),q.append(e)},a=()=>{const e=document.querySelector(".loader");e&&e.remove()},E=()=>{u.style.display="block"},s=()=>{u.style.display="none"};let p=1,m=40,l="",g;f.addEventListener("submit",async e=>{e.preventDefault(),y(),d.innerHTML="",l=v.value.trim(),p=1;try{if(l===""){s(),c.error({message:"Please enter a search term.",position:"center",transitionIn:"fadeInLeft"}),a();return}const t=await b();w(t),f.reset(),a(),E(),t.hits.length<m&&s(),t.hits.length===0&&(s(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",transitionIn:"fadeInLeft"}))}catch(t){handleError(t)}});u.addEventListener("click",async()=>{y();try{p+=1;const e=await b();w(e),a();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),(d.children.length>=g||e.hits.length<m)&&(c.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),s())}catch(e){handleError(e),a()}});async function b(){try{const e=new URLSearchParams({key:I,q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,page:p,per_page:m}),t=await L.get(`https://pixabay.com/api/?${e}`);return g=t.data.totalHits,t.data}catch(e){throw console.log(e),new Error("Failed to fetch images")}}const P=new S(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250});function w(e){const t=e.hits.map(n=>`
        <li class="gallery-item"><a href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}"></a>
          <p><b>Likes: </b>${n.likes}</p>
          <p><b>Views: </b>${n.views}</p>
          <p><b>Comments: </b>${n.comments}</p>
          <p><b>Downloads: </b>${n.downloads}</p>
        </li>`).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}
//# sourceMappingURL=commonHelpers.js.map
